temp/objects/Agenda__c.object
<CustomObject>
    <description>A list of subjects to be discussed.</description>
    <fields>
        <fullName>CreatedFromAgendaId__c</fullName>
        <description>Used to save the Id from the original (template) agenda record.</description>
        <label>Agenda Template</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsTemplate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Template</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KInId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Input Knowledge</label>
        <referenceTo>Kb__c</referenceTo>
        <relationshipLabel>Input Kb for Agenda</relationshipLabel>
        <relationshipName>kInAgenda</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KeyWords__c</fullName>
        <description>Important words separated by semi-colon.</description>
        <inlineHelpText>Important words separated by semi-colon.</inlineHelpText>
        <label>Key-Words</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MeetingId__c</fullName>
        <label>Meeting</label>
        <referenceTo>Meeting__c</referenceTo>
        <relationshipLabel>Agenda Of Meeting</relationshipLabel>
        <relationshipName>AgdMeet</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SubjectDescription__c</fullName>
        <label>Subject Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubjectId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subject</label>
        <referenceTo>Subject__c</referenceTo>
        <relationshipLabel>Agenda Subject</relationshipLabel>
        <relationshipName>SubjectOfAgenda</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agenda</label>
    <nameField>
        <label>Agenda Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agenda</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/classes/AgendaDAO.cls
public with sharing class AgendaDAO {

   private static final AgendaDAO instance = new AgendaDAO();    

   private AgendaDAO(){}

   public static AgendaDAO getInstance() {return instance;}

   public List<Agenda__c> getAgenda(){
      List<Agenda__c> lagdReturn;
      List<Agenda__c> agdList = [Select Id,IsTemplate__c,KInId__c,KeyWords__c,MeetingId__c,Name,SubjectDescription__c,SubjectId__c From Agenda__c]; 
      if(!agdList.isEmpty()) lagdReturn = agdList;
      else                   lagdReturn = new List<Agenda__c>();      
      return lagdReturn; 
   }

   public List<Agenda__c> getAgendaByTemplateId(String pMeetingId){
      List<Agenda__c> lagdReturn;
      List<Agenda__c> agdList = [Select Id,IsTemplate__c,KInId__c,KeyWords__c,MeetingId__c,Name,SubjectDescription__c,SubjectId__c From Agenda__c Where MeetingId__c = :pMeetingId And IsTemplate__c = True]; 
      if(!agdList.isEmpty()) lagdReturn = agdList;
      else                   lagdReturn = new List<Agenda__c>();      
      return lagdReturn; 
   }

   public Agenda__c getAgendaById(String pAgdId ){
      Agenda__c agd;
      try { agd = [Select Id,IsTemplate__c,KInId__c,KeyWords__c,MeetingId__c,Name,SubjectDescription__c,SubjectId__c From Agenda__c Where Id = :pAgdId limit 1]; }
      catch (Exception ex) { agd = new Agenda__c(); } 
      return agd;
   }

   public String getNewAgendaIdByAgdTptId(String pMtgId, String pAgdId ){ //Get New Agenda Id by Agenda Template Id
      String agdIdReturn;
      Agenda__c agd = new Agenda__c();
      try {
      	 agd = [Select Id 
      	          From Agenda__c
      	         Where MeetingId__c = :pMtgId 
      	           and CreatedFromAgendaId__c = :pAgdId limit 1];
      	 agdIdReturn = agd.Id;    
      }
      catch (Exception ex) {agdIdReturn = Null;} 
      return agdIdReturn;
   }
}