temp/objects/Attendee__c.object
<CustomObject>
    <description>All the people who will be part of a meeting.</description>
    <fields>
        <fullName>AgendaId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates where it comes from</description>
        <label>Agenda</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Agenda__c.MeetingId__c</field>
                <operation>equals</operation>
                <valueField>$Source.MeetingId__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Agenda__c</referenceTo>
        <relationshipLabel>Attendee Of Agenda</relationshipLabel>
        <relationshipName>AttendeeOfAgenda</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContactId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Attendee</relationshipLabel>
        <relationshipName>ContactAttendee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CreatedFromAttendeeId__c</fullName>
        <label>Attendee Template</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmployeeId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Attendee</relationshipLabel>
        <relationshipName>EmployeesAttendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HasConfirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>InviteeId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invitee</label>
        <referenceTo>Invitee__c</referenceTo>
        <relationshipLabel>Invitee Attendee</relationshipLabel>
        <relationshipName>Attendee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsTemplate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Should this record used as template with meeting template?</description>
        <label>Is Template</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JoinedBy__c</fullName>
        <defaultValue>&apos;Meeting Organizer&apos;</defaultValue>
        <label>Joined By</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>Key Word</fullName>
                </value>
                <value>
                    <fullName>Organizer</fullName>
                    <default>true</default>
                    <label>Organizer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KeyWords__c</fullName>
        <description>Informational field, just to let people know which key word was used to join the attendee to the meeting.</description>
        <label>Key-Words</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MeetingId__c</fullName>
        <label>Meeting</label>
        <referenceTo>Meeting__c</referenceTo>
        <relationshipLabel>Attendee</relationshipLabel>
        <relationshipName>MeetingsAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StatusEmail__c</fullName>
        <label>Status E-Mail</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Not Sent</fullName>
                </value>
                <value>
                    <fullName>Error found</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SupContactId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Contact</label>
        <referenceTo>SupContact__c</referenceTo>
        <relationshipLabel>Participants from Supplier Contact</relationshipLabel>
        <relationshipName>SupContactOfAttendee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>Attendee-{000000}</displayFormat>
        <label>Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/classes/AttendeeDAO.cls
public with sharing class AttendeeDAO {

   private static final AttendeeDAO instance = new AttendeeDAO();    

   private AttendeeDAO(){}

   public static AttendeeDAO getInstance() {return instance;}

   public List<Attendee__c> getAttendeeByMeetingId(String pMeetingId) {
      List<Attendee__c> latdReturn;
      try { latdReturn = [Select Id,Name,AgendaId__c,ContactId__c,EmployeeId__c,HasConfirmed__c,InviteeId__c,IsTemplate__c,JoinedBy__c,KeyWords__c,MeetingId__c,SupContactId__c,StatusEmail__c From Attendee__c Where MeetingId__c = :pMeetingId and AgendaId__c = null]; }
      catch (Exception ex) { latdReturn = new List<Attendee__c>(); }
      return latdReturn; 
   }

   public List<Attendee__c> getAttendeeByTemplateId(String pMeetingId) {
      List<Attendee__c> latdReturn;
      try { latdReturn = [Select Id,Name,AgendaId__c,ContactId__c,EmployeeId__c,HasConfirmed__c,InviteeId__c,IsTemplate__c,JoinedBy__c,KeyWords__c,MeetingId__c,SupContactId__c,StatusEmail__c From Attendee__c Where MeetingId__c = :pMeetingId And IsTemplate__c = True]; }
      catch (Exception ex) { latdReturn = new List<Attendee__c>(); }
      return latdReturn; 
   }

   public Attendee__c getAttendeeById(String pAtdId ){
      Attendee__c atd;
      try { atd = [Select Id,Name,ContactId__c,AgendaId__c,EmployeeId__c,HasConfirmed__c,InviteeId__c,IsTemplate__c,JoinedBy__c,KeyWords__c,MeetingId__c,SupContactId__c,StatusEmail__c From Attendee__c Where Id = :pAtdId limit 1]; }
      catch (Exception ex) { atd = new Attendee__c(); } 
      return atd;
   }
   
   public Attendee__c getAttendeeByEmployeeId(String pAgendaId,String pEmployeeId ){
      Attendee__c atd;
      try { atd = [Select Id,Name,ContactId__c,AgendaId__c,EmployeeId__c,HasConfirmed__c,InviteeId__c,IsTemplate__c,JoinedBy__c,KeyWords__c,MeetingId__c,SupContactId__c,StatusEmail__c From Attendee__c Where AgendaId__c = :pAgendaId and EmployeeId__c = :pEmployeeId limit 1]; }
      catch (Exception ex) { atd = new Attendee__c(); } 
      return atd;
   }

   public Attendee__c getAttendeeByInviteeId(String pAgendaId,String pInviteeId ){
      Attendee__c atd;
      try { atd = [Select Id,Name,ContactId__c,AgendaId__c,EmployeeId__c,HasConfirmed__c,InviteeId__c,IsTemplate__c,JoinedBy__c,KeyWords__c,MeetingId__c,SupContactId__c,StatusEmail__c From Attendee__c Where AgendaId__c = :pAgendaId and InviteeId__c = :pInviteeId limit 1]; }
      catch (Exception ex) { atd = new Attendee__c(); } 
      return atd;
   }

   public Attendee__c getAttendeeByContactId(String pAgendaId,String pContactId ){
      Attendee__c atd;
      try { atd = [Select Id,Name,ContactId__c,AgendaId__c,EmployeeId__c,HasConfirmed__c,InviteeId__c,IsTemplate__c,JoinedBy__c,KeyWords__c,MeetingId__c,SupContactId__c,StatusEmail__c From Attendee__c Where AgendaId__c = :pAgendaId and ContactId__c = :pContactId limit 1]; }
      catch (Exception ex) { atd = new Attendee__c(); } 
      return atd;
   }

   public Attendee__c getAttendeeBySupContactId(String pAgendaId,String pSupContactId ){
      Attendee__c atd;
      try { atd = [Select Id,Name,ContactId__c,AgendaId__c,EmployeeId__c,HasConfirmed__c,InviteeId__c,IsTemplate__c,JoinedBy__c,KeyWords__c,MeetingId__c,SupContactId__c,StatusEmail__c From Attendee__c Where AgendaId__c = :pAgendaId and ContactId__c = :pSupContactId limit 1]; }
      catch (Exception ex) { atd = new Attendee__c(); } 
      return atd;
   }

   public List<Attendee__c> getAttendeeByAgenda(String pAgendaId) {
      List<Attendee__c> latdReturn; 
      try { latdReturn = [Select Id,Name,ContactId__c,AgendaId__c,EmployeeId__c,HasConfirmed__c,InviteeId__c,IsTemplate__c,JoinedBy__c,KeyWords__c,MeetingId__c,SupContactId__c,StatusEmail__c From Attendee__c Where AgendaId__c = :pAgendaId]; } 
      catch (Exception ex) { latdReturn = new List<Attendee__c>(); }      
      return latdReturn; 
   }
   
   public String getNewAttendeeIdByAttTptId(String pMtgId, String pAttId ){ //Get New Attendee Id by Attendee Template Id
      String attIdReturn;
      Attendee__c att = new Attendee__c();
      try {
      	 att = [Select Id 
      	          From Attendee__c
      	         Where MeetingId__c = :pMtgid
      	           and CreatedFromAttendeeId__c = :pAttId limit 1];
      	 attIdReturn = att.Id;    
      }
      catch (Exception ex) {attIdReturn = Null;} 
      return attIdReturn;
   }
   
    public List<Attendee__c> getAttendeeWithoutMail(String pMeetingId) {
      List<Attendee__c> latdReturn;
      try { latdReturn = [Select Id,Name,AgendaId__c,ContactId__c,EmployeeId__c,HasConfirmed__c,InviteeId__c,IsTemplate__c,JoinedBy__c,KeyWords__c,MeetingId__c,SupContactId__c,StatusEmail__c From Attendee__c Where MeetingId__c = :pMeetingId and StatusEmail__c != 'Sent']; }
      catch (Exception ex) { latdReturn = new List<Attendee__c>(); }
      return latdReturn; 
   }
}