temp/objects/Connection__c.object
<CustomObject>
    <description>Records the relationship between Agenda Item and Employee( T2E) or Kbase or Minutes or Invitee or Supplier Contact or Contact related to it.</description>
    <fields>
        <fullName>AgendaId__c</fullName>
        <label>Agenda</label>
        <referenceTo>Agenda__c</referenceTo>
        <relationshipLabel>Connections By Key-Word</relationshipLabel>
        <relationshipName>AgendaConnection</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ConnectedField__c</fullName>
        <formula>HYPERLINK( Url__c ,  LinkName__c  , &quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Connected Field</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Connection</relationshipLabel>
        <relationshipName>ContactOfConnection</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EmployeeId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Connection</relationshipLabel>
        <relationshipName>EmployeeConnection</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InviteeId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invitee</label>
        <referenceTo>Invitee__c</referenceTo>
        <relationshipLabel>Connection</relationshipLabel>
        <relationshipName>InviteeConnection</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KeyWords__c</fullName>
        <description>Key word set responsible for connection creation.</description>
        <label>Key-Words</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LinkName__c</fullName>
        <label>Link Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SupContactId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Contact</label>
        <referenceTo>SupContact__c</referenceTo>
        <relationshipLabel>Connection</relationshipLabel>
        <relationshipName>SupContactOfAgenda</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Url__c</fullName>
        <label>Url</label>
        <type>Url</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <label>Connected With</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connection</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ConnectionDAO.cls
public with sharing class ConnectionDAO {

   private static final ConnectionDAO instance = new ConnectionDAO();    

   private ConnectionDAO(){}

   public static ConnectionDAO getInstance() {return instance;}

   public List<Connection__c> getConnectionOfPerson(String pAgendaId){
      List<Connection__c> lconnReturn;
      List<Connection__c> connList = [Select Id,Name,AgendaId__c,ConnectedField__c,ContactId__c,EmployeeId__c,InviteeId__c,KeyWords__c,LinkName__c,SupContactId__c,Url__c
                                        From Connection__c
                                       Where AgendaId__c = :pAgendaId
                                         and (EmployeeId__c   != null or EmployeeId__c   != '' or
                                              InviteeId__c    != Null or InviteeId__c    != '' or
                                              ContactId__c    != Null or ContactId__c    != '' or
                                              SupContactId__c != Null or SupContactId__c != '')];
      if(!connList.isEmpty()) lconnReturn = connList;
      else                    lconnReturn = new List<Connection__c>();      
      return lconnReturn; 
   }
}