temp/objects/ContactExpertise__c.object
<CustomObject>
    <description>A set of expertise of a customer (Contact) to be used as a participant in a meeting.</description>
    <fields>
        <fullName>ContactId__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Expertise</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Expertise__c</fullName>
        <label>Expertise</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KeyWords__c</fullName>
        <label>Key-Words</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Contact Expertise</label>
    <nameField>
        <displayFormat>ContactExpertise-{0000}</displayFormat>
        <label>Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Expertise</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

temp/classes/ContactExpertiseDAO.cls
public with sharing class ContactExpertiseDAO {

   private static final ContactExpertiseDAO instance = new ContactExpertiseDAO();    

   private ContactExpertiseDAO(){}

   public static ContactExpertiseDAO getInstance() {return instance;}

   public ContactExpertise__c getContactExpertiseById(String pCttsId ){
      ContactExpertise__c ctts;
      try { ctts = [Select Id,Name,Expertise__c,KeyWords__c From ContactExpertise__c Where Id = :pCttsId limit 1]; }
      catch (Exception ex) { ctts = new ContactExpertise__c(); } 
      return ctts;
   }
   
   public List<ContactExpertise__c> getContactExpertiseByKeyWord(String pKeyWord ){
      String sct = '%' + pKeyWord + '%';
      List<ContactExpertise__c> lContactExpertiseReturn = [Select Id,ContactId__c,ContactId__r.FirstName,ContactId__r.LastName,Expertise__c,KeyWords__c From ContactExpertise__c Where KeyWords__c like :sct];   
      if(lContactExpertiseReturn.isEmpty()) lContactExpertiseReturn = new List<ContactExpertise__c>();
      return lContactExpertiseReturn; 
   }
}