temp/objects/Decision__c.object
<CustomObject>
    <description>All decision taken and forwardings of a meeting.</description>
    <fields>
        <fullName>ActionStatus__c</fullName>
        <label>Action Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Done</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Business Development - Opportunity</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Create a Report</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Execute</fullName>
                </value>
                <value>
                    <fullName>Learn</fullName>
                </value>
                <value>
                    <fullName>Notify</fullName>
                </value>
                <value>
                    <fullName>Prepare</fullName>
                </value>
                <value>
                    <fullName>Schedule</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AttendeeId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Action Point Accountable</relationshipLabel>
        <relationshipName>AttendeeOfDecision</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ConnectedField__c</fullName>
        <formula>HYPERLINK(Url__c, LinkName__c, &quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DueDate__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LinkName__c</fullName>
        <label>Link Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MeetingId__c</fullName>
        <description>Id of the meeting</description>
        <label>Meeting</label>
        <referenceTo>Meeting__c</referenceTo>
        <relationshipLabel>Decisions Of Meeting</relationshipLabel>
        <relationshipName>DecisionsOfMeeting</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MinutesId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Minutes Item</label>
        <referenceTo>Minutes__c</referenceTo>
        <relationshipLabel>Decisions Of Minutes</relationshipLabel>
        <relationshipName>DecisionsOfMinutes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Id</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity from Meeting Decision</relationshipLabel>
        <relationshipName>OpportunityOfDecision</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Url__c</fullName>
        <label>Url</label>
        <type>Url</type>
    </fields>
    <label>Decision</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Decisions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/DecisionDAO.cls
public with sharing class DecisionDAO {

   private static final DecisionDAO instance = new DecisionDAO();    

   private DecisionDAO(){}

   public static DecisionDAO getInstance() {return instance;}

   public List<Decision__c> getDecision(){
      List<Decision__c> ldecReturn;
      List<Decision__c> decList = [Select Id,Name,Action__c,ActionStatus__c,AttendeeId__c,Description__c,DueDate__c,MeetingId__c,MinutesId__c,LinkName__c,Url__c,ConnectedField__c,OpportunityId__c From Decision__c]; 
      if(!decList.isEmpty()) ldecReturn = decList;
      else                   ldecReturn = new List<Decision__c>();      
      return ldecReturn; 
   }

   public Decision__c getDecisionById(String pDecId ){
      Decision__c dec;
      try { dec = [Select Id,Name,Action__c,ActionStatus__c,AttendeeId__c,Description__c,DueDate__c,MeetingId__c,MinutesId__c,LinkName__c,Url__c,ConnectedField__c,OpportunityId__c From Decision__c Where Id = :pDecId limit 1]; }
      catch (Exception ex) { dec =  new Decision__c(); } 
      return dec;
   }
}