temp/objects/Employee__c.object
<CustomObject>
    <description>Records data from organization&apos;s employees.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>EmployeeId__c</fullName>
        <externalId>true</externalId>
        <label>Employee Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Position</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Position.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Analyst</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant</fullName>
    </customValue>
    <customValue>
        <fullName>Auxiliary</fullName>
    </customValue>
    <customValue>
        <fullName>Boss</fullName>
    </customValue>
    <customValue>
        <fullName>CEO</fullName>
    </customValue>
    <customValue>
        <fullName>CFO</fullName>
    </customValue>
    <customValue>
        <fullName>Chief</fullName>
    </customValue>
    <customValue>
        <fullName>CIO</fullName>
    </customValue>
    <customValue>
        <fullName>Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>COO</fullName>
    </customValue>
    <customValue>
        <fullName>Coordinator</fullName>
    </customValue>
    <customValue>
        <fullName>Course Coordinator</fullName>
    </customValue>
    <customValue>
        <fullName>Director</fullName>
    </customValue>
    <customValue>
        <fullName>Full Professor</fullName>
    </customValue>
    <customValue>
        <fullName>Head</fullName>
    </customValue>
    <customValue>
        <fullName>Junior</fullName>
    </customValue>
    <customValue>
        <fullName>Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Middle</fullName>
    </customValue>
    <customValue>
        <fullName>President</fullName>
    </customValue>
    <customValue>
        <fullName>Researcher</fullName>
    </customValue>
    <customValue>
        <fullName>Scientist</fullName>
    </customValue>
    <customValue>
        <fullName>Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Superintendent</fullName>
    </customValue>
    <customValue>
        <fullName>Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Vice-Director</fullName>
    </customValue>
    <customValue>
        <fullName>Vice-President</fullName>
    </customValue>
    <customValue>
        <fullName>Programmer</fullName>
    </customValue>
    <customValue>
        <fullName>Developer</fullName>
    </customValue>
    <masterLabel>Position</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/EmployeeDAO.cls
public with sharing class EmployeeDAO {

   private static final EmployeeDAO instance = new EmployeeDAO();    

   private EmployeeDAO(){}

   public static EmployeeDAO getInstance() {return instance;}

   public List<Employee__c> getEmployee(){
      List<Employee__c> lempReturn;
      List<Employee__c> empList = [Select Id,Name,Email__c,EmployeeId__c,Phone__c,Position__c,Role__c From Employee__c]; 
      if(!empList.isEmpty()) lempReturn = empList;
      else                   lempReturn = new List<Employee__c>();      
      return lempReturn;
   }

   public Employee__c getEmployeeById(String pEmployeeId ){
      Employee__c emp;
      try { emp = [Select Id,Name,Email__c,EmployeeId__c,Phone__c,Position__c,Role__c From Employee__c Where Id = :pEmployeeId limit 1]; }
      catch (Exception ex) { emp = new Employee__c(); }
      return emp;
   }
}