temp/objects/EventLog__c.object
<CustomObject>
    <description>Table to record information, warning and error events</description>
    <fields>
        <fullName>DateTime__c</fullName>
        <label>Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Information</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>EventLog</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventLog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Kb__c.object
<CustomObject>
    <description>A set of knowledge gathered across the organization.</description>
    <fields>
        <fullName>KOut__c</fullName>
        <label>Generated Knowledge</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>KeyWords__c</fullName>
        <description>Important words separated by semi-colon.</description>
        <inlineHelpText>Important words separated by semi-colon.</inlineHelpText>
        <label>Key-Words</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LessonLearned__c</fullName>
        <label>Lesson Learned</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MinutesId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Minutes of Meeting</label>
        <referenceTo>Minutes__c</referenceTo>
        <relationshipLabel>Knowledge Base</relationshipLabel>
        <relationshipName>MinutesKB</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubjectId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subject Id</label>
        <referenceTo>Subject__c</referenceTo>
        <relationshipLabel>Knowledge Base</relationshipLabel>
        <relationshipName>SubjectsKB</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KBase</label>
    <nameField>
        <displayFormat>KB-{000000}</displayFormat>
        <label>Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KBase</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/objects/Minutes__c.object
<CustomObject>
    <description>The official record of the proceedings of a meeting</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>KbRecorded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Kb Recorded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KeyWords__c</fullName>
        <description>Important words separated by semi-colon.</description>
        <inlineHelpText>Important words separated by semi-colon.</inlineHelpText>
        <label>Key-Words</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordKb__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Record Kb?</label>
        <type>Checkbox</type>
    </fields>
    <label>Minutes</label>
    <nameField>
        <label>Minutes Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Minute</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/MinutesBO.cls
public with sharing class MinutesBO {

   private static final MinutesBO instance = new MinutesBO();    

   private MinutesBO(){}
    
   public static MinutesBO getInstance() { return instance; }

   public void recordKb( List<Minutes__c> pminutes ) { /* Records Kb from Minutes */
      EventLog__c      evtlog = new EventLog__c();
      Minutes__c          min = new Minutes__c();
      List<Minutes__c> updmin = new List<Minutes__c>();  
      Kb__c                kb = new Kb__c();

      try {
         for (Minutes__c lminutes:pminutes) {
            if (lminutes.RecordKb__c == true) { 
               kb  = KbDAO.getInstance().getKbByMinutesId(lminutes.Id);
               if (kb.Id == null) {
                  kb = new Kb__c(
                     KeyWords__c  = lminutes.KeyWords__c,
                     KOut__c      = lminutes.Description__c, LessonLearned__c = Null,
                     MinutesId__c = lminutes.Id,             SubjectId__c     = Null,
                     Title__c     = lminutes.Name);
                  insert kb;   
               }
               min = MinutesDAO.getInstance().getMinutesById(lminutes.Id);
               min.KbRecorded__c = True;
               updmin.add(min); 
            }
         }
         ProcessControl.ignoredByTrigger = True;
         if (updmin.size() > 0) update updmin;
      }
      catch( Exception ex ) {
         evtlog = new EventLog__c(DateTime__c = System.now(), Process__c = 'MinutesBO', Type__c = 'Error',Description__c = '>>> ERROR: ' + ex.getMessage() + ' / ' + ex.getTypeName());
         insert evtlog;
      }          
   }
}