temp/objects/Invitee__c.object
<CustomObject>
    <description>People outside organization and different from supplier contact.</description>
    <fields>
        <fullName>EMail__c</fullName>
        <label>E-Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Expertise__c</fullName>
        <label>Expertise</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KeyWords__c</fullName>
        <label>Key Words</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MobilePhone__c</fullName>
        <label>Mobile Phone</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dr</fullName>
                </value>
                <value>
                    <fullName>Sir</fullName>
                </value>
                <value>
                    <fullName>Ma&apos;am</fullName>
                </value>
                <value>
                    <fullName>Phd</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invitee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invitees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

temp/classes/InviteeDAO.cls
public with sharing class InviteeDAO {

   private static final InviteeDAO instance = new InviteeDAO();    

   private InviteeDAO(){}

   public static InviteeDAO getInstance() {return instance;}

   public List<Invitee__c> getInvitee(){
      List<Invitee__c> linvReturn = [Select Id,Name,Expertise__c,KeyWords__c,Title__c,Email__c,MobilePhone__c From Invitee__c]; 
      if(linvReturn.isEmpty()) linvReturn = new List<Invitee__c>();      
      return linvReturn;
   }

   public Invitee__c getInviteeById(String pInviteeId ){
      Invitee__c inv;
      try { inv = [Select Id,Name,Expertise__c,KeyWords__c,Title__c,Email__c,MobilePhone__c From Invitee__c Where Id = :pInviteeId limit 1]; }
      catch (Exception ex) { inv = new Invitee__c(); }
      return inv;
   }
   
   public List<Invitee__c> getInviteeByKeyWord(String pKeyWord ){
      String inv = '%' + pKeyWord + '%';
      List<Invitee__c> lInviteeReturn = [Select Id,Name,Expertise__c,KeyWords__c,Title__c,Email__c,MobilePhone__c From Invitee__c Where KeyWords__c like :inv];   
      if(lInviteeReturn.isEmpty()) lInviteeReturn = new List<Invitee__c>();      
      return lInviteeReturn; 
   }
}