temp/objects/Kb__c.object
<CustomObject>
    <description>A set of knowledge gathered across the organization.</description>
    <fields>
        <fullName>KOut__c</fullName>
        <label>Generated Knowledge</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>KeyWords__c</fullName>
        <description>Important words separated by semi-colon.</description>
        <inlineHelpText>Important words separated by semi-colon.</inlineHelpText>
        <label>Key-Words</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LessonLearned__c</fullName>
        <label>Lesson Learned</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MinutesId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Minutes of Meeting</label>
        <referenceTo>Minutes__c</referenceTo>
        <relationshipLabel>Knowledge Base</relationshipLabel>
        <relationshipName>MinutesKB</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubjectDescription__c</fullName>
        <label>Subject Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubjectId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subject Id</label>
        <referenceTo>Subject__c</referenceTo>
        <relationshipLabel>Knowledge Base</relationshipLabel>
        <relationshipName>SubjectsKB</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KBase</label>
    <nameField>
        <displayFormat>KB-{000000}</displayFormat>
        <label>Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KBase</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/KbDAO.cls
public with sharing class KbDAO {

   private static final KbDAO instance = new KbDAO();    

   private KbDAO(){}

   public static KbDAO getInstance() {return instance;}

   public List<Kb__c> getKb(){
      List<Kb__c> lkbaseReturn;
      List<Kb__c> kbaseList = [Select Id,Name,KOut__c,KeyWords__c,LessonLearned__c,MinutesId__c,SubjectDescription__c,SubjectId__c,Title__c From Kb__c]; 
      if(!kbaseList.isEmpty()) lkbaseReturn = kbaseList;
      else                   lkbaseReturn = new List<Kb__c>();      
      return lkbaseReturn; 
   }

   public Kb__c getKbById(String pKbId ){
      Kb__c kbase;
      try { kbase = [Select Id,Name,KOut__c,KeyWords__c,LessonLearned__c,MinutesId__c,SubjectDescription__c,SubjectId__c,Title__c From Kb__c Where Id = :pKbId limit 1]; }
      catch (Exception ex) { kbase = new Kb__c(); } 
      return kbase;
   }

   public Kb__c getKbByMinutesId(String pMinId ){
      Kb__c kbase;
      try { kbase = [Select Id,Name,KOut__c,KeyWords__c,LessonLearned__c,MinutesId__c,SubjectDescription__c,SubjectId__c,Title__c From Kb__c Where MinutesId__c = :pMinId limit 1]; }
      catch (Exception ex) { kbase = new Kb__c(); }
      return kbase;
   }

   public List<Kb__c> getKbByKeyWord(String pKeyWord ){
      String kw = '%' + pKeyWord + '%';
      List<Kb__c> lkbaseReturn;
      List<Kb__c> kbaseList = [Select Id,Name,KOut__c,KeyWords__c,LessonLearned__c,MinutesId__c,SubjectDescription__c,SubjectId__c,Title__c From Kb__c Where KeyWords__c like :kw];   
      if(!kbaseList.isEmpty()) lkbaseReturn = kbaseList;
      else                   lkbaseReturn = new List<Kb__c>();      
      return lkbaseReturn; 
   }
}