temp/objects/Meeting__c.object
<CustomObject>
    <description>The record of a meeting</description>
    <fields>
        <fullName>CreatedFromMeetingId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Set meeting template Id to copy information from.</description>
        <label>Meeting Template</label>
        <referenceTo>Meeting__c</referenceTo>
        <relationshipLabel>Meetings Created from Template</relationshipLabel>
        <relationshipName>MeetingOfTemplate</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DateTime__c</fullName>
        <description>Meeting date and time</description>
        <label>Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Objectives up to 2000 characters.</description>
        <inlineHelpText>Objectives up to 2000 characters</inlineHelpText>
        <label>Description</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>How often this meeting occurs.</description>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Bimonthly</fullName>
                </value>
                <value>
                    <fullName>Biweekly</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Extraordinary</fullName>
                </value>
                <value>
                    <fullName>Hourly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Ordinary</fullName>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Six-monthly</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsTemplate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identify the meeting as a template for creating new meetings bringing some basic information and attendees.</description>
        <label>Is Template</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MeetingType__c</fullName>
        <label>Meeting Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consultative</fullName>
                </value>
                <value>
                    <fullName>Definition</fullName>
                </value>
                <value>
                    <fullName>Deliberative</fullName>
                </value>
                <value>
                    <fullName>Expository</fullName>
                </value>
                <value>
                    <fullName>Information</fullName>
                </value>
                <value>
                    <fullName>Not defined</fullName>
                </value>
                <value>
                    <fullName>Work</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProjectId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Id of the project that generated this meeting, if exists.</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Meeting</relationshipLabel>
        <relationshipName>ProjectsOfMeetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title of the meeting</description>
        <label>Title</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <description>Where the meeting will take place</description>
        <label>Venue</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Meeting</label>
    <nameField>
        <displayFormat>MEET-{000000}</displayFormat>
        <label>Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MeetingDAO.cls
public with sharing class MeetingDAO {

   private static final MeetingDAO instance = new MeetingDAO();    

   private MeetingDAO(){}

   public static MeetingDAO getInstance() {return instance;}

   public List<Meeting__c> getMeeting(){
      List<Meeting__c> listMeetingReturn;
      try {listMeetingReturn = [Select DateTime__c,Description__c,Frequency__c,Id,IsTemplate__c,CreatedFromMeetingId__c,MeetingType__c,Name,ProjectId__c,Title__c,Venue__c From Meeting__c];} 
      catch (Exception ex) {listMeetingReturn = new List<Meeting__c>();}      
      return listMeetingReturn; 
   }
 
   public Meeting__c getMeetingById(String pMeeId ){
      Meeting__c meetingReturn;
      try {meetingReturn = [Select DateTime__c,Description__c,Frequency__c,Id,IsTemplate__c,CreatedFromMeetingId__c,MeetingType__c,Name,ProjectId__c,Title__c,Venue__c From Meeting__c Where Id = :pMeeId limit 1];}
      catch (Exception ex) {meetingReturn = new Meeting__c();} 
      return meetingReturn;
   }

   public List<Meeting__c> getMeetingsById(List<Meeting__c> pListMeetId ){
      List<Meeting__c> listMeetingReturn;
      try {listMeetingReturn = [Select DateTime__c,Description__c,Frequency__c,Id,IsTemplate__c,CreatedFromMeetingId__c,MeetingType__c,Name,ProjectId__c,Title__c,Venue__c From Meeting__c Where Id in :pListMeetId];}
      catch (Exception ex) {listMeetingReturn.add(new Meeting__c());} 
      return listMeetingReturn;
   }

}