temp/objects/Minutes__c.object
<CustomObject>
    <description>The official record of the proceedings of a meeting</description>
    <fields>
        <fullName>AgendaItemId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agenda Item</label>
        <referenceTo>Agenda__c</referenceTo>
        <relationshipLabel>Minutes of Meeting</relationshipLabel>
        <relationshipName>AgdItemsMinutes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AttendeeId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Minutes of Meeting</relationshipLabel>
        <relationshipName>AttendeesMinutes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>KeyWords__c</fullName>
        <description>Important words separated by semi-colon.</description>
        <inlineHelpText>Important words separated by semi-colon.</inlineHelpText>
        <label>Key-Words</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MeetingId__c</fullName>
        <label>Meeting</label>
        <referenceTo>Meeting__c</referenceTo>
        <relationshipLabel>Minutes of Meeting</relationshipLabel>
        <relationshipName>MinutesMeetings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Minutes</label>
    <nameField>
        <label>Minutes Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Minute</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/MinutesDAO.cls
public with sharing class MinutesDAO {

   private static final MinutesDAO instance = new MinutesDAO();    

   private MinutesDAO(){}

   public static MinutesDAO getInstance() {return instance;}

   public List<Minutes__c> getMinutes(){
      List<Minutes__c> lminReturn;
      List<Minutes__c> minList = [Select Id,Name,AgendaItemId__c,AttendeeId__c,Description__c,KeyWords__c,MeetingId__c From Minutes__c]; 
      if(!minList.isEmpty()) lminReturn = minList;
      else                   lminReturn = new List<Minutes__c>();      
      return lminReturn; 
   }

   public Minutes__c getMinutesById(String pMinId ){
      Minutes__c min;
      try { min = [Select Id,Name,AgendaItemId__c,AttendeeId__c,Description__c,KeyWords__c,MeetingId__c From Minutes__c Where Id = :pMinId limit 1]; }
      catch (Exception ex) { min = new Minutes__c(); }
      return min;
   }

   public List<Minutes__c> getMinutesByKeyWord(String pKeyWord ){
      String kw = '%' + pKeyWord + '%';
      List<Minutes__c> lminReturn;
      List<Minutes__c> minList = [Select Id,Name,AgendaItemId__c,AttendeeId__c,Description__c,KeyWords__c,MeetingId__c From Minutes__c Where KeyWords__c like :kw];   
      if(!minList.isEmpty()) lminReturn = minList;
      else                   lminReturn = new List<Minutes__c>();      
      return lminReturn; 
   }
}