temp/objects/Subject__c.object
<CustomObject>
    <description>The subject to be discussed</description>
    <fields>
        <fullName>ConcatenatedField__c</fullName>
        <label>Concatenated Field</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Subject Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KnowledgeArea__c</fullName>
        <label>Knowledge Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KnowledgeArea</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SearchString__c</fullName>
        <formula>HYPERLINK(
   LEFT($Api.Partner_Server_URL_260, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_260)) + Id,
    ConcatenatedField__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Search String</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <description>Skill related to Knowledge Area</description>
        <label>Skill</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>KnowledgeArea__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Skill</valueSetName>
        </valueSet>
    </fields>
    <label>Subject</label>
    <nameField>
        <displayFormat>Subject-{000000}</displayFormat>
        <label>Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subject</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/KnowledgeArea.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Academy/University</fullName>
    </customValue>
    <customValue>
        <fullName>Accommodation</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting</fullName>
    </customValue>
    <customValue>
        <fullName>Administration</fullName>
    </customValue>
    <customValue>
        <fullName>Aeronautics</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospace</fullName>
    </customValue>
    <customValue>
        <fullName>Artificial Intelligence</fullName>
    </customValue>
    <customValue>
        <fullName>Aviation</fullName>
    </customValue>
    <customValue>
        <fullName>Biology</fullName>
    </customValue>
    <customValue>
        <fullName>Building</fullName>
    </customValue>
    <customValue>
        <fullName>Chemistry</fullName>
    </customValue>
    <customValue>
        <fullName>Comercial</fullName>
    </customValue>
    <customValue>
        <fullName>Computer Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Computer Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Computer Science</fullName>
    </customValue>
    <customValue>
        <fullName>Culture</fullName>
    </customValue>
    <customValue>
        <fullName>Engeneering</fullName>
    </customValue>
    <customValue>
        <fullName>Entertainment</fullName>
    </customValue>
    <customValue>
        <fullName>Fashion</fullName>
    </customValue>
    <customValue>
        <fullName>Finances</fullName>
    </customValue>
    <customValue>
        <fullName>Fishing</fullName>
    </customValue>
    <customValue>
        <fullName>Food</fullName>
    </customValue>
    <customValue>
        <fullName>Fundraising</fullName>
    </customValue>
    <customValue>
        <fullName>Geography</fullName>
    </customValue>
    <customValue>
        <fullName>Health</fullName>
    </customValue>
    <customValue>
        <fullName>Hosting</fullName>
    </customValue>
    <customValue>
        <fullName>Human Rights</fullName>
    </customValue>
    <customValue>
        <fullName>Hunting</fullName>
    </customValue>
    <customValue>
        <fullName>Industry</fullName>
    </customValue>
    <customValue>
        <fullName>Information Systems</fullName>
    </customValue>
    <masterLabel>Knowledge Area</masterLabel>
</GlobalValueSet>

temp/globalValueSets/Skill.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Academic Presentation</fullName>
    </customValue>
    <customValue>
        <fullName>BPM</fullName>
    </customValue>
    <customValue>
        <fullName>BPMN</fullName>
    </customValue>
    <customValue>
        <fullName>Business Plan</fullName>
    </customValue>
    <customValue>
        <fullName>Business Presentation</fullName>
    </customValue>
    <customValue>
        <fullName>Business Rules</fullName>
    </customValue>
    <customValue>
        <fullName>Class Diagram</fullName>
    </customValue>
    <customValue>
        <fullName>Compliance</fullName>
    </customValue>
    <customValue>
        <fullName>Data Model</fullName>
    </customValue>
    <customValue>
        <fullName>Development</fullName>
    </customValue>
    <customValue>
        <fullName>Digital Media Strategies</fullName>
    </customValue>
    <customValue>
        <fullName>Entity-Relationship Model</fullName>
    </customValue>
    <customValue>
        <fullName>Face-to-Face Approach</fullName>
    </customValue>
    <customValue>
        <fullName>Governance</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Acquisition</fullName>
    </customValue>
    <customValue>
        <fullName>Management Accounting</fullName>
    </customValue>
    <customValue>
        <fullName>Management Theories</fullName>
    </customValue>
    <customValue>
        <fullName>Object Oriented Analysis</fullName>
    </customValue>
    <customValue>
        <fullName>Object Oriented Programming</fullName>
    </customValue>
    <customValue>
        <fullName>Plane Building</fullName>
    </customValue>
    <customValue>
        <fullName>Plane Crashing</fullName>
    </customValue>
    <customValue>
        <fullName>PMI</fullName>
    </customValue>
    <customValue>
        <fullName>PMI Knowledge Areas</fullName>
    </customValue>
    <customValue>
        <fullName>Process Mapping</fullName>
    </customValue>
    <customValue>
        <fullName>Project Management</fullName>
    </customValue>
    <customValue>
        <fullName>Quality Control</fullName>
    </customValue>
    <customValue>
        <fullName>Six Sigma</fullName>
    </customValue>
    <customValue>
        <fullName>Standards</fullName>
    </customValue>
    <customValue>
        <fullName>State Change Diagram</fullName>
    </customValue>
    <customValue>
        <fullName>System Requirements</fullName>
    </customValue>
    <description>Subtopics</description>
    <masterLabel>Skill</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/SubjectDAO.cls
public with sharing class SubjectDAO {

   private static final SubjectDAO instance = new SubjectDAO();    

   private SubjectDAO(){}

   public static SubjectDAO getInstance() {return instance;}

   public List<Subject__c> getSubject(){
      List<Subject__c> lsbjReturn;
      List<Subject__c> sbjList = [Select Id, Name, KnowledgeArea__c, Skill__c, Description__c, ConcatenatedField__c, SearchString__c From Subject__c]; 
      if(!sbjList.isEmpty()) lsbjReturn = sbjList;
      else                   lsbjReturn = new List<Subject__c>();      
      return lsbjReturn; 
   }

   public Subject__c getSubjectById(String pSbjId ){
      Subject__c sbj;
      try { sbj = [Select Id, Name, KnowledgeArea__c, Skill__c, Description__c, ConcatenatedField__c, SearchString__c From Subject__c Where Id = :pSbjId limit 1]; }
      catch (Exception ex) { sbj = new Subject__c(); } 
      return sbj;
   }
   
   public Subject__c getSubjectByName(String pSbjName ){
      Subject__c sbj;
      try { sbj = [Select Id, Name, KnowledgeArea__c, Skill__c, Description__c, ConcatenatedField__c, SearchString__c From Subject__c Where Name = :pSbjName limit 1]; }
      catch (Exception ex) { sbj = new Subject__c(); } 
      return sbj;
   }
}