temp/objects/SupContact__c.object
<CustomObject>
    <description>The minimal data from the suppliers employee.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Expertise__c</fullName>
        <label>Expertise</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KeyWords__c</fullName>
        <label>Key-Words</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Position</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SupplierId__c</fullName>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Contacts of Supplier</relationshipLabel>
        <relationshipName>ContactsOfSupplier</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SupContact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SupContact</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Position.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Analyst</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant</fullName>
    </customValue>
    <customValue>
        <fullName>Auxiliary</fullName>
    </customValue>
    <customValue>
        <fullName>Boss</fullName>
    </customValue>
    <customValue>
        <fullName>CEO</fullName>
    </customValue>
    <customValue>
        <fullName>CFO</fullName>
    </customValue>
    <customValue>
        <fullName>Chief</fullName>
    </customValue>
    <customValue>
        <fullName>CIO</fullName>
    </customValue>
    <customValue>
        <fullName>Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>COO</fullName>
    </customValue>
    <customValue>
        <fullName>Coordinator</fullName>
    </customValue>
    <customValue>
        <fullName>Course Coordinator</fullName>
    </customValue>
    <customValue>
        <fullName>Director</fullName>
    </customValue>
    <customValue>
        <fullName>Full Professor</fullName>
    </customValue>
    <customValue>
        <fullName>Head</fullName>
    </customValue>
    <customValue>
        <fullName>Junior</fullName>
    </customValue>
    <customValue>
        <fullName>Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Middle</fullName>
    </customValue>
    <customValue>
        <fullName>President</fullName>
    </customValue>
    <customValue>
        <fullName>Researcher</fullName>
    </customValue>
    <customValue>
        <fullName>Scientist</fullName>
    </customValue>
    <customValue>
        <fullName>Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Superintendent</fullName>
    </customValue>
    <customValue>
        <fullName>Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Vice-Director</fullName>
    </customValue>
    <customValue>
        <fullName>Vice-President</fullName>
    </customValue>
    <customValue>
        <fullName>Programmer</fullName>
    </customValue>
    <customValue>
        <fullName>Developer</fullName>
    </customValue>
    <masterLabel>Position</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/SupContactDAO.cls
public with sharing class SupContactDAO {

   private static final SupContactDAO instance = new SupContactDAO();    

   private SupContactDAO(){}

   public static SupContactDAO getInstance() {return instance;}

   public SupContact__c getSupContactById(String pSCttId ){
      SupContact__c sCtt;
      try { sCtt = [Select Id,Name,Email__c,Expertise__c,KeyWords__c,Phone__c,Position__c,Role__c,SupplierId__c From SupContact__c Where Id = :pSCttId limit 1]; }
      catch (Exception ex) { sCtt = new SupContact__c(); } 
      return sCtt;
   }
   
   public List<SupContact__c> getSupContactByKeyWord(String pKeyWord ){
      String sct = '%' + pKeyWord + '%';
      List<SupContact__c> lSupContactReturn = [Select Id,Name,Email__c,Expertise__c,KeyWords__c,Phone__c,Position__c,Role__c,SupplierId__c From SupContact__c Where KeyWords__c like :sct];   
      if(lSupContactReturn.isEmpty()) lSupContactReturn = new List<SupContact__c>();
      return lSupContactReturn; 
   }
   
}