temp/objects/T2E__c.object
<CustomObject>
    <description>Registers a specific tacit knowledge of someone&apos;s brain into the database making it explicit</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EmployeeId__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Knowledge of Employee</relationshipLabel>
        <relationshipName>KnowledgesOfEmployee</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>KeyWords__c</fullName>
        <label>Key-Words</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KnowledgeArea__c</fullName>
        <label>Knowledge Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>KnowledgeArea</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>T2E</label>
    <nameField>
        <label>Knowledge</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>T2E</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/KnowledgeArea.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Academy/University</fullName>
    </customValue>
    <customValue>
        <fullName>Accommodation</fullName>
    </customValue>
    <customValue>
        <fullName>Accounting</fullName>
    </customValue>
    <customValue>
        <fullName>Administration</fullName>
    </customValue>
    <customValue>
        <fullName>Aeronautics</fullName>
    </customValue>
    <customValue>
        <fullName>Aerospace</fullName>
    </customValue>
    <customValue>
        <fullName>Artificial Intelligence</fullName>
    </customValue>
    <customValue>
        <fullName>Aviation</fullName>
    </customValue>
    <customValue>
        <fullName>Biology</fullName>
    </customValue>
    <customValue>
        <fullName>Building</fullName>
    </customValue>
    <customValue>
        <fullName>Chemistry</fullName>
    </customValue>
    <customValue>
        <fullName>Comercial</fullName>
    </customValue>
    <customValue>
        <fullName>Computer Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Computer Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Computer Science</fullName>
    </customValue>
    <customValue>
        <fullName>Culture</fullName>
    </customValue>
    <customValue>
        <fullName>Engeneering</fullName>
    </customValue>
    <customValue>
        <fullName>Entertainment</fullName>
    </customValue>
    <customValue>
        <fullName>Fashion</fullName>
    </customValue>
    <customValue>
        <fullName>Finances</fullName>
    </customValue>
    <customValue>
        <fullName>Fishing</fullName>
    </customValue>
    <customValue>
        <fullName>Food</fullName>
    </customValue>
    <customValue>
        <fullName>Fundraising</fullName>
    </customValue>
    <customValue>
        <fullName>Geography</fullName>
    </customValue>
    <customValue>
        <fullName>Health</fullName>
    </customValue>
    <customValue>
        <fullName>Hosting</fullName>
    </customValue>
    <customValue>
        <fullName>Human Rights</fullName>
    </customValue>
    <customValue>
        <fullName>Hunting</fullName>
    </customValue>
    <customValue>
        <fullName>Industry</fullName>
    </customValue>
    <customValue>
        <fullName>Information Systems</fullName>
    </customValue>
    <masterLabel>Knowledge Area</masterLabel>
</GlobalValueSet>

temp/classes/T2EDAO.cls
public with sharing class T2EDAO {

   private static final T2EDAO instance = new T2EDAO();    

   private T2EDAO(){}

   public static T2EDAO getInstance() {return instance;}

   public List<T2E__c> getT2E(){
      List<T2E__c> lt2eReturn;
      List<T2E__c> t2eList = [Select Id,Name,Description__c,EmployeeId__c,KeyWords__c,KnowledgeArea__c,Title__c From T2E__c]; 
      if(!t2eList.isEmpty()) lt2eReturn = t2eList;
      else                   lt2eReturn = new List<T2E__c>();      
      return lt2eReturn;
   }

   public T2E__c getT2EById(String pT2EId ){
      T2E__c t2e;
      try { t2e = [Select Id,Name,Description__c,EmployeeId__c,KeyWords__c,KnowledgeArea__c,Title__c From T2E__c Where Id = :pT2EId limit 1]; }
      catch (Exception ex) { t2e = new T2E__c(); }
      return t2e;
   }

   public List<T2E__c> getT2EByKeyWord(String pKeyWord ){
      String kw = '%' + pKeyWord + '%';
      List<T2E__c> lt2eReturn;
      List<T2E__c> t2eList = [Select Id,Name,Description__c,EmployeeId__c,KeyWords__c,KnowledgeArea__c,Title__c From T2E__c Where KeyWords__c like :kw];   
      if(!t2eList.isEmpty()) lt2eReturn = t2eList;
      else                   lt2eReturn = new List<T2E__c>();      
      return lt2eReturn; 
   }
}